


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."estado_sugerencia" AS ENUM (
    'PENDIENTE',
    'APROBADO',
    'RECHAZADO'
);


ALTER TYPE "public"."estado_sugerencia" OWNER TO "postgres";


CREATE TYPE "public"."turno_tipo" AS ENUM (
    'manana',
    'tarde'
);


ALTER TYPE "public"."turno_tipo" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."hash_password"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF TG_OP = 'INSERT' OR NEW."contrasenia" IS DISTINCT FROM OLD."contrasenia" THEN
        NEW."contrasenia" := crypt(NEW."contrasenia", gen_salt('bf'));
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."hash_password"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."cadena" (
    "id_cadena" bigint NOT NULL,
    "establecimiento" character varying NOT NULL,
    "codigo_cadena" character varying NOT NULL,
    "nombre_particular" character varying,
    "empresa_cadena" character varying
);


ALTER TABLE "public"."cadena" OWNER TO "postgres";


ALTER TABLE "public"."cadena" ALTER COLUMN "id_cadena" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CADENA_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."distrito" (
    "distrito" bigint NOT NULL,
    "nombre_distrito" character varying NOT NULL
);


ALTER TABLE "public"."distrito" OWNER TO "postgres";


COMMENT ON TABLE "public"."distrito" IS 'Información sobre los distritos (código y nombre asociado)';



ALTER TABLE "public"."distrito" ALTER COLUMN "distrito" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DISTRITO_distrito_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."entidad" (
    "id_entidad" bigint NOT NULL,
    "codigo_bancosol" "text" NOT NULL,
    "nombre" "text",
    "vinculado_bancosol" boolean DEFAULT false,
    "domicilio" "text",
    "cp" character varying(5),
    "id_usuario_contacto" bigint
);


ALTER TABLE "public"."entidad" OWNER TO "postgres";


ALTER TABLE "public"."entidad" ALTER COLUMN "id_entidad" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ENTIDADES_idEntidad_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tienda" (
    "id_tienda" bigint NOT NULL,
    "cp" character varying(5),
    "domicilio" character varying,
    "id_cadena" bigint
);


ALTER TABLE "public"."tienda" OWNER TO "postgres";


ALTER TABLE "public"."tienda" ALTER COLUMN "id_tienda" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TIENDA_idTienda_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."turno" (
    "id_turno" bigint NOT NULL,
    "id_campania" bigint,
    "id_tienda" bigint,
    "fecha" "date" NOT NULL,
    "turno" "public"."turno_tipo",
    "observaciones" "text",
    "id_entidad" bigint,
    CONSTRAINT "turno_relaciones_check" CHECK ((("id_campania" IS NOT NULL) OR ("id_tienda" IS NOT NULL) OR ("id_entidad" IS NOT NULL)))
);


ALTER TABLE "public"."turno" OWNER TO "postgres";


COMMENT ON COLUMN "public"."turno"."turno" IS 'Valores: manana, tarde';



ALTER TABLE "public"."turno" ALTER COLUMN "id_turno" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TURNO_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."zona" (
    "zona_geografica" "text" NOT NULL,
    "id_zona" bigint NOT NULL
);


ALTER TABLE "public"."zona" OWNER TO "postgres";


ALTER TABLE "public"."zona" ALTER COLUMN "id_zona" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ZONA_idZona_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."asignacion_tienda" (
    "id_campania" bigint NOT NULL,
    "id_tienda" bigint NOT NULL,
    "id_usuario" bigint NOT NULL,
    "id_entidad" bigint
);


ALTER TABLE "public"."asignacion_tienda" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."asignacion_zona" (
    "id_campania" bigint NOT NULL,
    "id_zona" bigint NOT NULL,
    "id_usuario" bigint NOT NULL,
    "rol_en_campania" character varying(50) NOT NULL
);


ALTER TABLE "public"."asignacion_zona" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."campania" (
    "id_campania" bigint NOT NULL,
    "nombre" character varying(100) NOT NULL,
    "fecha_inicio" "date",
    "fecha_fin" "date",
    "tipo" character varying(50)
);


ALTER TABLE "public"."campania" OWNER TO "postgres";


ALTER TABLE "public"."campania" ALTER COLUMN "id_campania" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."campania_idCampania_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contacto_adicional" (
    "id_contacto" bigint NOT NULL,
    "id_entidad" bigint NOT NULL,
    "nombre_completo" "text",
    "puesto" "text",
    "telefono" character varying(20),
    "email" "text",
    "id_usuario" bigint
);


ALTER TABLE "public"."contacto_adicional" OWNER TO "postgres";


ALTER TABLE "public"."contacto_adicional" ALTER COLUMN "id_contacto" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contactos_adicionales_idcontacto_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cp" (
    "cp" character varying(5) NOT NULL,
    "localidad" character varying NOT NULL,
    "distrito" bigint,
    "municipio" character varying,
    "id_zona" bigint NOT NULL
);


ALTER TABLE "public"."cp" OWNER TO "postgres";


COMMENT ON TABLE "public"."cp" IS 'Códigos postales';



CREATE TABLE IF NOT EXISTS "public"."sugerencia_cambio" (
    "id_sugerencia" bigint NOT NULL,
    "tipo_entidad" character varying(255) NOT NULL,
    "id_entidad_original" bigint NOT NULL,
    "datos_propuestos" "text",
    "id_propuesto_por" bigint NOT NULL,
    "fecha_propuesta" timestamp with time zone DEFAULT "now"() NOT NULL,
    "estado" "public"."estado_sugerencia" DEFAULT 'PENDIENTE'::"public"."estado_sugerencia" NOT NULL,
    "id_revisado_por" bigint,
    "fecha_revision" timestamp with time zone
);


ALTER TABLE "public"."sugerencia_cambio" OWNER TO "postgres";


COMMENT ON COLUMN "public"."sugerencia_cambio"."tipo_entidad" IS 'El tipo de la entidad que se sugiere cambiar (ej: VOLUNTARIO, TIENDA)';



COMMENT ON COLUMN "public"."sugerencia_cambio"."id_entidad_original" IS 'El ID de la fila en la tabla original (ej: el id_voluntario)';



COMMENT ON COLUMN "public"."sugerencia_cambio"."datos_propuestos" IS 'Un objeto JSON con los nuevos valores propuestos';



ALTER TABLE "public"."sugerencia_cambio" ALTER COLUMN "id_sugerencia" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sugerencia_cambio_id_sugerencia_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tienda_campania" (
    "id_tienda" bigint NOT NULL,
    "id_campania" bigint NOT NULL,
    "id_responsable_tienda" bigint,
    "id_coordinador" bigint,
    "id_capitan" bigint,
    "num_cajas" bigint,
    "participa" boolean
);


ALTER TABLE "public"."tienda_campania" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."turnos_voluntarios" (
    "id_turno" bigint NOT NULL,
    "id_voluntario" bigint NOT NULL
);


ALTER TABLE "public"."turnos_voluntarios" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."usuario" (
    "id_usuario" bigint NOT NULL,
    "nombre_completo" "text" NOT NULL,
    "email" "text" NOT NULL,
    "contrasenia" "text" NOT NULL,
    "telefono" "text",
    "rol" "text" NOT NULL,
    "domicilio" "text",
    "cp" character varying(5),
    CONSTRAINT "usuario_email_valido" CHECK (("email" ~* '^[^@]+@[^@]+\.[^@]+$'::"text")),
    CONSTRAINT "usuario_telefono_valido" CHECK (("telefono" ~ '^[0-9+\- ]*$'::"text"))
);


ALTER TABLE "public"."usuario" OWNER TO "postgres";


COMMENT ON TABLE "public"."usuario" IS 'Datos de todos los usuarios';



ALTER TABLE "public"."usuario" ALTER COLUMN "id_usuario" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usuario_idUsuario_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."voluntario" (
    "id_voluntario" bigint NOT NULL,
    "id_entidad" bigint NOT NULL,
    "nombre" "text",
    "apellido_1" "text",
    "apellido_2" "text",
    "email" "text"
);


ALTER TABLE "public"."voluntario" OWNER TO "postgres";


ALTER TABLE "public"."voluntario" ALTER COLUMN "id_voluntario" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."voluntarios_id_voluntarios_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."cp"
    ADD CONSTRAINT "CP_pkey" PRIMARY KEY ("cp");



ALTER TABLE ONLY "public"."distrito"
    ADD CONSTRAINT "DISTRITO_pkey" PRIMARY KEY ("distrito");



ALTER TABLE ONLY "public"."entidad"
    ADD CONSTRAINT "ENTIDADES_pkey" PRIMARY KEY ("id_entidad");



ALTER TABLE ONLY "public"."tienda"
    ADD CONSTRAINT "TIENDA_pkey" PRIMARY KEY ("id_tienda");



ALTER TABLE ONLY "public"."turno"
    ADD CONSTRAINT "TURNO_pkey" PRIMARY KEY ("id_turno");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "USUARIO_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("id_usuario");



ALTER TABLE ONLY "public"."voluntario"
    ADD CONSTRAINT "VOLUNTARIOS_pkey" PRIMARY KEY ("id_voluntario");



ALTER TABLE ONLY "public"."zona"
    ADD CONSTRAINT "ZONA_pkey" PRIMARY KEY ("id_zona");



ALTER TABLE ONLY "public"."zona"
    ADD CONSTRAINT "ZONA_zonaGeografica_key" UNIQUE ("zona_geografica");



ALTER TABLE ONLY "public"."asignacion_tienda"
    ADD CONSTRAINT "asignacion_tiendas_pkey" PRIMARY KEY ("id_campania", "id_tienda", "id_usuario");



ALTER TABLE ONLY "public"."asignacion_zona"
    ADD CONSTRAINT "asignacion_zonas_pkey" PRIMARY KEY ("id_campania", "id_zona", "id_usuario", "rol_en_campania");



ALTER TABLE ONLY "public"."cadena"
    ADD CONSTRAINT "cadena_codigo_cadena_key" UNIQUE ("codigo_cadena");



ALTER TABLE ONLY "public"."cadena"
    ADD CONSTRAINT "cadena_pk" PRIMARY KEY ("id_cadena");



ALTER TABLE ONLY "public"."campania"
    ADD CONSTRAINT "campana_pkey" PRIMARY KEY ("id_campania");



ALTER TABLE ONLY "public"."contacto_adicional"
    ADD CONSTRAINT "contactos_adicionales_pkey" PRIMARY KEY ("id_contacto");



ALTER TABLE ONLY "public"."turnos_voluntarios"
    ADD CONSTRAINT "pk_turnos_voluntarios" PRIMARY KEY ("id_turno", "id_voluntario");



ALTER TABLE ONLY "public"."sugerencia_cambio"
    ADD CONSTRAINT "sugerencia_cambio_pkey" PRIMARY KEY ("id_sugerencia");



ALTER TABLE ONLY "public"."tienda_campania"
    ADD CONSTRAINT "tienda_campania_pkey" PRIMARY KEY ("id_tienda", "id_campania");



CREATE INDEX "idx_asignaciontiendas_idcampania" ON "public"."asignacion_tienda" USING "btree" ("id_campania");



CREATE INDEX "idx_asignaciontiendas_idtienda" ON "public"."asignacion_tienda" USING "btree" ("id_tienda");



CREATE INDEX "idx_asignaciontiendas_idusuario" ON "public"."asignacion_tienda" USING "btree" ("id_usuario");



CREATE INDEX "idx_asignacionzonas_idcampania" ON "public"."asignacion_zona" USING "btree" ("id_campania");



CREATE INDEX "idx_asignacionzonas_idusuario" ON "public"."asignacion_zona" USING "btree" ("id_usuario");



CREATE INDEX "idx_asignacionzonas_idzona" ON "public"."asignacion_zona" USING "btree" ("id_zona");



CREATE INDEX "idx_contactosadicionales_identidad" ON "public"."contacto_adicional" USING "btree" ("id_entidad");



CREATE INDEX "idx_contactosadicionales_idusuario" ON "public"."contacto_adicional" USING "btree" ("id_usuario");



CREATE INDEX "idx_cp_distrito" ON "public"."cp" USING "btree" ("distrito");



CREATE INDEX "idx_cp_idzona" ON "public"."cp" USING "btree" ("id_zona");



CREATE INDEX "idx_entidades_cp" ON "public"."entidad" USING "btree" ("cp");



CREATE INDEX "idx_entidades_idusuariocontacto" ON "public"."entidad" USING "btree" ("id_usuario_contacto");



CREATE INDEX "idx_sugerencia_estado" ON "public"."sugerencia_cambio" USING "btree" ("estado");



CREATE INDEX "idx_sugerencia_tipo_entidad" ON "public"."sugerencia_cambio" USING "btree" ("tipo_entidad");



CREATE INDEX "idx_tienda_cp" ON "public"."tienda" USING "btree" ("cp");



CREATE INDEX "idx_tienda_idcadena" ON "public"."tienda" USING "btree" ("id_cadena");



CREATE INDEX "idx_tiendacampania_idcampania" ON "public"."tienda_campania" USING "btree" ("id_campania");



CREATE INDEX "idx_turno_idcampania" ON "public"."turno" USING "btree" ("id_campania");



CREATE INDEX "idx_turno_identidad" ON "public"."turno" USING "btree" ("id_entidad");



CREATE INDEX "idx_turno_idtienda" ON "public"."turno" USING "btree" ("id_tienda");



CREATE OR REPLACE TRIGGER "trigger_hash_password" BEFORE INSERT OR UPDATE ON "public"."usuario" FOR EACH ROW EXECUTE FUNCTION "public"."hash_password"();



ALTER TABLE ONLY "public"."cp"
    ADD CONSTRAINT "CP_distrito_fkey" FOREIGN KEY ("distrito") REFERENCES "public"."distrito"("distrito");



ALTER TABLE ONLY "public"."cp"
    ADD CONSTRAINT "CP_idZona_fkey" FOREIGN KEY ("id_zona") REFERENCES "public"."zona"("id_zona") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."turno"
    ADD CONSTRAINT "TURNO_idEntidad_fkey" FOREIGN KEY ("id_entidad") REFERENCES "public"."entidad"("id_entidad");



ALTER TABLE ONLY "public"."turno"
    ADD CONSTRAINT "TURNO_idTienda_fkey" FOREIGN KEY ("id_tienda") REFERENCES "public"."tienda"("id_tienda");



ALTER TABLE ONLY "public"."voluntario"
    ADD CONSTRAINT "VOLUNTARIOS_idEntidad_fkey" FOREIGN KEY ("id_entidad") REFERENCES "public"."entidad"("id_entidad");



ALTER TABLE ONLY "public"."asignacion_tienda"
    ADD CONSTRAINT "asignacion_tiendas_idcampania_fkey" FOREIGN KEY ("id_campania") REFERENCES "public"."campania"("id_campania");



ALTER TABLE ONLY "public"."asignacion_tienda"
    ADD CONSTRAINT "asignacion_tiendas_identidad_fkey" FOREIGN KEY ("id_entidad") REFERENCES "public"."entidad"("id_entidad");



ALTER TABLE ONLY "public"."asignacion_tienda"
    ADD CONSTRAINT "asignacion_tiendas_idtienda_fkey" FOREIGN KEY ("id_tienda") REFERENCES "public"."tienda"("id_tienda");



ALTER TABLE ONLY "public"."asignacion_tienda"
    ADD CONSTRAINT "asignacion_tiendas_idusuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."asignacion_zona"
    ADD CONSTRAINT "asignacion_zonas_idcampania_fkey" FOREIGN KEY ("id_campania") REFERENCES "public"."campania"("id_campania");



ALTER TABLE ONLY "public"."asignacion_zona"
    ADD CONSTRAINT "asignacion_zonas_idusuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."asignacion_zona"
    ADD CONSTRAINT "asignacion_zonas_idzona_fkey" FOREIGN KEY ("id_zona") REFERENCES "public"."zona"("id_zona");



ALTER TABLE ONLY "public"."contacto_adicional"
    ADD CONSTRAINT "contactos_adicionales_identidad_fkey" FOREIGN KEY ("id_entidad") REFERENCES "public"."entidad"("id_entidad");



ALTER TABLE ONLY "public"."contacto_adicional"
    ADD CONSTRAINT "contactosadicionales_idusuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."entidad"
    ADD CONSTRAINT "entidad_usuario_fk" FOREIGN KEY ("id_usuario_contacto") REFERENCES "public"."usuario"("id_usuario") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."entidad"
    ADD CONSTRAINT "entidades_cp_fkey" FOREIGN KEY ("cp") REFERENCES "public"."cp"("cp");



ALTER TABLE ONLY "public"."tienda"
    ADD CONSTRAINT "fk_tienda_cadena" FOREIGN KEY ("id_cadena") REFERENCES "public"."cadena"("id_cadena") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."turnos_voluntarios"
    ADD CONSTRAINT "fk_turnos_voluntarios_turno" FOREIGN KEY ("id_turno") REFERENCES "public"."turno"("id_turno") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."turnos_voluntarios"
    ADD CONSTRAINT "fk_turnos_voluntarios_voluntario" FOREIGN KEY ("id_voluntario") REFERENCES "public"."voluntario"("id_voluntario") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sugerencia_cambio"
    ADD CONSTRAINT "sugerencia_cambio_id_propuesto_por_fkey" FOREIGN KEY ("id_propuesto_por") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."sugerencia_cambio"
    ADD CONSTRAINT "sugerencia_cambio_id_revisado_por_fkey" FOREIGN KEY ("id_revisado_por") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."tienda_campania"
    ADD CONSTRAINT "tienda_campania_idcampania_fkey" FOREIGN KEY ("id_campania") REFERENCES "public"."campania"("id_campania");



ALTER TABLE ONLY "public"."tienda_campania"
    ADD CONSTRAINT "tienda_campania_idcapitan_fkey" FOREIGN KEY ("id_capitan") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."tienda_campania"
    ADD CONSTRAINT "tienda_campania_idcoordinador_fkey" FOREIGN KEY ("id_coordinador") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."tienda_campania"
    ADD CONSTRAINT "tienda_campania_idresponsable_fkey" FOREIGN KEY ("id_responsable_tienda") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE ONLY "public"."tienda_campania"
    ADD CONSTRAINT "tienda_campania_idtienda_fkey" FOREIGN KEY ("id_tienda") REFERENCES "public"."tienda"("id_tienda");



ALTER TABLE ONLY "public"."tienda"
    ADD CONSTRAINT "tienda_cp_fkey" FOREIGN KEY ("cp") REFERENCES "public"."cp"("cp") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."turno"
    ADD CONSTRAINT "turno_idcampania_fkey" FOREIGN KEY ("id_campania") REFERENCES "public"."campania"("id_campania");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "usuario_cp_fkey" FOREIGN KEY ("cp") REFERENCES "public"."cp"("cp") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE "public"."asignacion_tienda" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."asignacion_zona" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cadena" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."campania" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contacto_adicional" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cp" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."distrito" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."entidad" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "full_access_authenticated" ON "public"."usuario" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_asignaciontiendas" ON "public"."asignacion_tienda" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_asignacionzonas" ON "public"."asignacion_zona" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_cadena" ON "public"."cadena" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_campania" ON "public"."campania" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_contactos" ON "public"."contacto_adicional" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_cp" ON "public"."cp" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_distrito" ON "public"."distrito" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_entidades" ON "public"."entidad" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_tienda" ON "public"."tienda" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_tiendacampania" ON "public"."tienda_campania" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_turno" ON "public"."turno" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_voluntarios" ON "public"."voluntario" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "full_access_authenticated_zona" ON "public"."zona" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."sugerencia_cambio" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tienda" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tienda_campania" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."turno" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."turnos_voluntarios" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."usuario" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."voluntario" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."zona" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."asignacion_tienda";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."asignacion_zona";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."tienda_campania";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."turno";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."hash_password"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."hash_password"() TO "service_role";


















GRANT ALL ON TABLE "public"."cadena" TO "anon";
GRANT ALL ON TABLE "public"."cadena" TO "authenticated";
GRANT ALL ON TABLE "public"."cadena" TO "service_role";



GRANT ALL ON SEQUENCE "public"."CADENA_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CADENA_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CADENA_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."distrito" TO "anon";
GRANT ALL ON TABLE "public"."distrito" TO "authenticated";
GRANT ALL ON TABLE "public"."distrito" TO "service_role";



GRANT ALL ON SEQUENCE "public"."DISTRITO_distrito_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DISTRITO_distrito_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DISTRITO_distrito_seq" TO "service_role";



GRANT ALL ON TABLE "public"."entidad" TO "authenticated";
GRANT ALL ON TABLE "public"."entidad" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ENTIDADES_idEntidad_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ENTIDADES_idEntidad_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ENTIDADES_idEntidad_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tienda" TO "anon";
GRANT ALL ON TABLE "public"."tienda" TO "authenticated";
GRANT ALL ON TABLE "public"."tienda" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TIENDA_idTienda_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TIENDA_idTienda_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TIENDA_idTienda_seq" TO "service_role";



GRANT ALL ON TABLE "public"."turno" TO "authenticated";
GRANT ALL ON TABLE "public"."turno" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TURNO_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TURNO_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TURNO_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."zona" TO "anon";
GRANT ALL ON TABLE "public"."zona" TO "authenticated";
GRANT ALL ON TABLE "public"."zona" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ZONA_idZona_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ZONA_idZona_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ZONA_idZona_seq" TO "service_role";



GRANT ALL ON TABLE "public"."asignacion_tienda" TO "authenticated";
GRANT ALL ON TABLE "public"."asignacion_tienda" TO "service_role";



GRANT ALL ON TABLE "public"."asignacion_zona" TO "authenticated";
GRANT ALL ON TABLE "public"."asignacion_zona" TO "service_role";



GRANT ALL ON TABLE "public"."campania" TO "authenticated";
GRANT ALL ON TABLE "public"."campania" TO "service_role";



GRANT ALL ON SEQUENCE "public"."campania_idCampania_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."campania_idCampania_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."campania_idCampania_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contacto_adicional" TO "authenticated";
GRANT ALL ON TABLE "public"."contacto_adicional" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contactos_adicionales_idcontacto_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contactos_adicionales_idcontacto_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contactos_adicionales_idcontacto_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cp" TO "anon";
GRANT ALL ON TABLE "public"."cp" TO "authenticated";
GRANT ALL ON TABLE "public"."cp" TO "service_role";



GRANT ALL ON TABLE "public"."sugerencia_cambio" TO "anon";
GRANT ALL ON TABLE "public"."sugerencia_cambio" TO "authenticated";
GRANT ALL ON TABLE "public"."sugerencia_cambio" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sugerencia_cambio_id_sugerencia_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sugerencia_cambio_id_sugerencia_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sugerencia_cambio_id_sugerencia_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tienda_campania" TO "authenticated";
GRANT ALL ON TABLE "public"."tienda_campania" TO "service_role";



GRANT ALL ON TABLE "public"."turnos_voluntarios" TO "anon";
GRANT ALL ON TABLE "public"."turnos_voluntarios" TO "authenticated";
GRANT ALL ON TABLE "public"."turnos_voluntarios" TO "service_role";



GRANT ALL ON TABLE "public"."usuario" TO "authenticated";
GRANT ALL ON TABLE "public"."usuario" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usuario_idUsuario_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."usuario_idUsuario_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usuario_idUsuario_seq" TO "service_role";



GRANT ALL ON TABLE "public"."voluntario" TO "anon";
GRANT ALL ON TABLE "public"."voluntario" TO "authenticated";
GRANT ALL ON TABLE "public"."voluntario" TO "service_role";



GRANT ALL ON SEQUENCE "public"."voluntarios_id_voluntarios_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."voluntarios_id_voluntarios_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."voluntarios_id_voluntarios_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































